### ISSUE TITLE
Remove this repo

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/cold-storage#1]
@DanVanAtta @ron-murhammer 
The only thing this repo contains is a docx version of the Rule book available [on the website](http://www.triplea-game.org/files/TripleA_RuleBook.pdf)
This repo should probably be deleted

**Comment by ron-murhammer** [comment]
Agree unless @DanVanAtta has plans to put other assets in here anytime soon.

**Comment by RoiEXLab** [comment]
Bumping... @DanVanAtta

**Comment by DanVanAtta** [comment]
We may want to keep this for anything we want stored but not downloaded when building installers. The assets repo is cloned when building installers, which slows that down.  Something like:  https://github.com/triplea-game/assets/blob/master/rulebooks/TripleA_RuleBook.pdf, perhaps should be stored here instead of in assets.

**Comment by RoiEXLab** [comment]
@DanVanAtta What about removing it for now and recreating it, when we need it again?

**Comment by RoiEXLab** [comment]
@DanVanAtta Bumping this because there's been some change to the triplea-maps/Project repo.
In my opinion, there's no value in keeping this repository, if we want a direct link to the game rules PDF, we can reference the URL over at the website repository or via triplea-game.org directly.

**Comment by DanVanAtta** [comment]
sure, let's remove. I created this repo as a compromise to move the docx to a different location, with more time and data it's pretty clear we do not need this file.
